// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlvx0l0mnwmYFhASV8oUMiDscAWNFEd9o',
    appId: '1:284534914320:web:9176070f71146afdfd3995',
    messagingSenderId: '284534914320',
    projectId: 'appmuabanchungcu',
    authDomain: 'appmuabanchungcu.firebaseapp.com',
    storageBucket: 'appmuabanchungcu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFATFcbIyuitnhpHS25AbO1JI3cKhNWBo',
    appId: '1:284534914320:android:e0745f174522b527fd3995',
    messagingSenderId: '284534914320',
    projectId: 'appmuabanchungcu',
    storageBucket: 'appmuabanchungcu.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlvx0l0mnwmYFhASV8oUMiDscAWNFEd9o',
    appId: '1:284534914320:web:fd7d55e089aa5838fd3995',
    messagingSenderId: '284534914320',
    projectId: 'appmuabanchungcu',
    authDomain: 'appmuabanchungcu.firebaseapp.com',
    storageBucket: 'appmuabanchungcu.firebasestorage.app',
  );
}
